# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
    # Repo in which the release will be created.
    # Default is extracted from the origin remote URL or empty if its private hosted.
    # Note: it can only be one: either github or gitlab or gitea
    github:
        owner: LadySerena
        name: dbus-api
before:
    hooks:
        # You may remove this if you don't use go modules.
        - go mod download
builds:
    -   env:
            - CGO_ENABLED=0
        main: ./cmd/world-downloader
archives:
    -   replacements:
            linux: Linux
            amd64: x86_64
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
