openapi: 3.0.1
info:
    title: DBus API
    description: API to interface with Systemd
    version: 1.0.0
servers:
    -   url: 'https://minecraft.serenacodes.com'
paths:
    /service:
        get:
            security:
                -   token: []
            summary: Returns the status of the configured systemd service
            responses:
                '200':
                    description: query ran successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/service-status'
                '401':
                    $ref: '#/components/responses/UnauthorizedError'
                '500':
                    description: internal server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/api-error'
        post:
            security:
                -   token: []
            summary: Changes the state of the configured service
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/service-change'
            responses:
                '200':
                    description: service was changed
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/service-status'
                '401':
                    $ref: '#/components/responses/UnauthorizedError'
                '500':
                    description: internal server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/api-error'

components:
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid
    securitySchemes:
        basicAuth:
            type: http
            scheme: basic
    schemas:
        service-change:
            properties:
                operation:
                    type: string
                    enum:
                        - start
                        - stop
                        - restart
        service-status:
            properties:
                service-name:
                    type: string
                active:
                    type: string
                    enum:
                        - active
                        - inactive
                sub-status:
                    type: string
                    enum:
                        - exited
                        - running
                        - waiting
                        - dead
        api-error:
            properties:
                status:
                    type: integer
                    format: int32
                reason:
                    type: string
