steps:
  - name: golang:1.15
    args:
      - go
      - build
      - './cmd/dbus-api'
  - name: openjdk:11-slim
    entrypoint: bash
    args:
      - "./gradlew"
      - "buildPackagePreCompiled"

