steps:
  - name: golang:1.15
    args:
      - go
      - build
      - './cmd/dbus-api'
    env:
      - "CGO_ENABLED=0" #static compilation to avoid glib issues
  - name: openjdk:11-slim
    entrypoint: bash
    args:
      - "./gradlew"
      - "buildPackagePreCompiled"
      - "-Ptag=$TAG_NAME"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gsutil
    args:
      - "cp"
      - "build/distributions/${_PACKAGE_NAME}_${TAG_NAME}_amd64.deb"
      - "gs://$_BUCKET/"
substitutions:
  _BUCKET: debian-v1.platform.serenacodes.com
  _PACKAGE_NAME: dbus-api
