steps:
  - name: golang:1.15
    args:
      - go
      - build
      - './cmd/dbus-api'
    env:
      - "CGO_ENABLED=0" #static compilation to avoid glib issues
  - name: openjdk:11-slim
    entrypoint: bash
    args:
      - "./gradlew"
      - "buildPackagePreCompiled"

